import Head from 'next/head'
import Header from '../../components/header/header'
import Contents from '../../components/contents/contents'
import Footer from '../../components/footer/footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"></link>
      </Head>

      < Header />
      <Contents />
      < Footer />
    </>
  )
}
