import Head from 'next/head'
import { Header } from '/components/header/header'
import Contents from '/components/contents/contents'
import { Footer } from '/components/footer/footer'
import { Breadcrumbs } from '/components/breadcrumbs/breadcrumbs'

export default function Home() {
  return (
    <>
      <Head>
        <title>Site Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      < Header />
      < Breadcrumbs />
      <Contents />
      < Footer />

    </>
  )
}
